
version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector
    environment:
      - K8S_NAMESPACE=opb # Para testar o tópico "opb-metrics"
      # - K8S_NAMESPACE=outro # Para testar o tópico "otel-metrics"
      
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      # - OTEL_RESOURCE_ATTRIBUTES=service.name=fastapi-app
      # - OTEL_TRACES_EXPORTER=otlp
      # - OTEL_METRICS_EXPORTER=otlp
      # - OTEL_LOGS_EXPORTER=otlp
      # - OTEL_TRACES_SAMPLER=always_on
      # - OTEL_TRACES_SAMPLER_ARG=1

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.36.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config", "/etc/otel-collector-config.yaml"]
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"

  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  mimir:
    image: grafana/mimir:latest
    ports:
      - "9000:9000"

volumes:
  grafana-storage:
    driver: local
